### ISSUE TITLE
KeyError: 'blocks'

### ISSUE THREAD

**Issue by maxuhuii** [hjf1997/USTD#2]
在forecasting时会报错：

**Comment by maxuhuii** [comment]
Traceback (most recent call last):
  File "/hom/USTD-master_0/train.py", line 25, in <module>
    model = create_model(opt, model_config)      # create a model given opt.model and other options
  File "/home/USTD-master_0/models/__init__.py", line 70, in create_model
    instance = model(opt, model_config)
  File "/home/USTD-master_0/models/stdiffusion/stdiffusionfore_model.py", line 48, in __init__
    self.netEncoder = GWaveNetEncoder(model_config['wavenet'])
  File "/home/USTD-master_0/models/stdiffusion/gwavenet.py", line 55, in __init__
    self.blocks = model_config['blocks']
KeyError: 'blocks'

**Comment by hjf1997** [comment]
Thanks for pointing out the issue.
It seems I caused some code discrepancies when doing the ablation studies.
I have cleared them, [please check](https://github.com/hjf1997/USTD/blob/ef04869c8f1fa252a41fa705495d69c82a47c0b9/models/stdiffusion/gwavenet.py#L53).

**Comment by maxuhuii** [comment]
Thanks for you apply!

**Comment by maxuhuii** [comment]
Thanks for your apply!
